### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by Zruto** [abcdef2000/R2RNet#10]
在RetinexNet中作者设计了LOL的数据集，里面包含500张图片，同时作者在训练模型的时候又使用了1000张合成的图片，那我在比较LOL数据集上结果的时候，也需要使用这1000张合成的图片吗？其他现有的论文中他们的LOL指标是不是也使用了这1000张合成图片呢？

**Comment by abcdef2000** [comment]
我们使用的是500张
