### ISSUE TITLE
inference 耗时问题

### ISSUE THREAD

**Issue by zhangyunming** [abcdef2000/R2RNet#11]
你好，如果一张手机拍图大概在3000*4000分辨率，大概inference时间再gpu和cpu下要多少时间。
我在用cpu测试，感觉时间很长

**Comment by abcdef2000** [comment]
你好，由于资源有限，我没有尝试过这么大分辨率图像的推理，在1080Ti上对1080x720的图像处理时间大概在1.2s左右，cpu也没有测试过，如果您那边资源充足可以尝试一下哈哈哈哈
