### ISSUE TITLE
下载的预训练权重压缩文件损坏

### ISSUE THREAD

**Issue by Bigtuo** [abcdef2000/R2RNet#12]

**Comment by Zruto** [comment]
> _No description provided._

RuntimeError: Error(s) in loading state_dict for RelightNet:
	Missing key(s) in state_dict: "EnhanceModule0.Enhance_conv0_1.weight", "EnhanceModule0.Enhance_conv0_1.bias", "EnhanceModule0.Enhance_conv0_2.weight", "EnhanceModule0.Enhance_conv0_2.bias", "EnhanceModule0.conv4.weight", "EnhanceModule0.conv4.bias", "EnhanceModule0.Enhance_subsampling0.weight", "EnhanceModule0.Enhance_subsampling0.bias", "EnhanceModule0.conv5.weight", "EnhanceModule0.conv5.bias", "EnhanceModule0.conv6.weight", "EnhanceModule0.conv6.bias", "EnhanceModule0.conv7.weight", "EnhanceModule0.conv7.bias", "EnhanceModule0.conv8.weight", "EnhanceModule0.conv8.bias", "EnhanceModule0.conv9.weight", "EnhanceModule0.conv9.bias", "EnhanceModule0.Enhance_subsampling1.weight", "EnhanceModule0.Enhance_subsampling1.bias", "EnhanceModule0.conv10.weight", "EnhanceModule0.conv10.bias", "EnhanceModule0.conv11.weight", "EnhanceModule0.conv11.bias", "EnhanceModule0.conv12.weight", "EnhanceModule0.conv12.bias", "EnhanceModule0.conv13.weight", "EnhanceModule0.conv13.bias", "EnhanceModule0.conv14.weight", "EnhanceModule0.conv14.bias", "EnhanceModule0.Enhance_subsampling2.weight", "EnhanceModule0.Enhance_subsampling2.bias", "EnhanceModule0.conv15.weight", "EnhanceModule0.conv15.bias", "EnhanceModule0.conv16.weight", "EnhanceModule0.conv16.bias", "EnhanceModule0.conv17.weight", "EnhanceModule0.conv17.bias", "EnhanceModule0.conv18.weight", "EnhanceModule0.conv18.bias", "EnhanceModule0.conv19.weight", "EnhanceModule0.conv19.bias", "EnhanceModule0.Enhance_deconv0.weight", "EnhanceModule0.Enhance_deconv0.bias", "EnhanceModule0.conv20.weight", "EnhanceModule0.conv20.bias", "EnhanceModule0.conv21.weight", "EnhanceModule0.conv21.bias", "EnhanceModule0.conv22.weight", "EnhanceModule0.conv22.bias", "EnhanceModule0.conv23.weight", "EnhanceModule0.conv23.bias", "EnhanceModule0.conv24.weight", "EnhanceModule0.conv24.bias", "EnhanceModule0.Enhance_deconv1.weight", "EnhanceModule0.Enhance_deconv1.bias", "EnhanceModule0.conv25.weight", "EnhanceModule0.conv25.bias", "EnhanceModule0.conv26.weight", "EnhanceModule0.conv26.bias", "EnhanceModule0.conv27.weight", "EnhanceModule0.conv27.bias", "EnhanceModule0.conv28.weight", "EnhanceModule0.conv28.bias", "EnhanceModule0.conv29.weight", "EnhanceModule0.conv29.bias", "EnhanceModule0.Enhance_deconv2.weight", "EnhanceModule0.Enhance_deconv2.bias", "EnhanceModule0.Enhanceout0.weight", "EnhanceModule0.Enhanceout0.bias", "EnhanceModule0.Enhanceout1.weight", "EnhanceModule0.Enhanceout1.bias", "EnhanceModule0.Enhanceout2.weight", "EnhanceModule0.Enhanceout2.bias", "EnhanceModule1.conv15_0.weight", "EnhanceModule1.conv15_0.bias", "EnhanceModule1.Enhance_deconv0.weight", "EnhanceModule1.Enhance_deconv0.bias", "EnhanceModule1.Enhance_deconv1.weight", "EnhanceModule1.Enhance_deconv1.bias", "EnhanceModule1.Enhance_deconv2.weight", "EnhanceModule1.Enhance_deconv2.bias", "EnhanceModule2.Enhance_conv0_1.weight", "EnhanceModule2.Enhance_conv0_1.bias", "EnhanceModule2.Enhance_conv0_2.weight", "EnhanceModule2.Enhance_conv0_2.bias", "EnhanceModule2.conv0.weight", "EnhanceModule2.conv0.bias", "EnhanceModule2.conv1.weight", "EnhanceModule2.conv1.bias", "EnhanceModule2.conv2.weight", "EnhanceModule2.conv2.bias", "EnhanceModule2.conv3.weight", "EnhanceModule2.conv3.bias", "EnhanceModule2.conv4.weight", "EnhanceModule2.conv4.bias", "EnhanceModule2.Enhance_subsampling0.weight", "EnhanceModule2.Enhance_subsampling0.bias", "EnhanceModule2.conv5.weight", "EnhanceModule2.conv5.bias", "EnhanceModule2.conv6.weight", "EnhanceModule2.conv6.bias", "EnhanceModule2.conv7.weight", "EnhanceModule2.conv7.bias", "EnhanceModule2.conv8.weight", "EnhanceModule2.conv8.bias", "EnhanceModule2.conv9.weight", "EnhanceModule2.conv9.bias", "EnhanceModule2.Enhance_subsampling1.weight", "EnhanceModule2.Enhance_subsampling1.bias", "EnhanceModule2.conv10.weight", "EnhanceModule2.conv10.bias", "EnhanceModule2.conv11.weight", "EnhanceModule2.conv11.bias", "EnhanceModule2.conv12.weight", "EnhanceModule2.conv12.bias", "EnhanceModule2.conv13.weight", "EnhanceModule2.conv13.bias", "EnhanceModule2.conv14.weight", "EnhanceModule2.conv14.bias", "EnhanceModule2.Enhance_subsampling2.weight", "EnhanceModule2.Enhance_subsampling2.bias", "EnhanceModule2.conv15.weight", "EnhanceModule2.conv15.bias", "EnhanceModule2.conv16.weight", "EnhanceModule2.conv16.bias", "EnhanceModule2.conv17.weight", "EnhanceModule2.conv17.bias", "EnhanceModule2.conv18.weight", "EnhanceModule2.conv18.bias", "EnhanceModule2.conv19.weight", "EnhanceModule2.conv19.bias", "EnhanceModule2.Enhance_deconv0.weight", "EnhanceModule2.Enhance_deconv0.bias", "EnhanceModule2.conv20.weight", "EnhanceModule2.conv20.bias", "EnhanceModule2.conv21.weight", "EnhanceModule2.conv21.bias", "EnhanceModule2.conv22.weight", "EnhanceModule2.conv22.bias", "EnhanceModule2.conv23.weight", "EnhanceModule2.conv23.bias", "EnhanceModule2.conv24.weight", "EnhanceModule2.conv24.bias", "EnhanceModule2.Enhance_deconv1.weight", "EnhanceModule2.Enhance_deconv1.bias", "EnhanceModule2.conv25.weight", "EnhanceModule2.conv25.bias", "EnhanceModule2.conv26.weight", "EnhanceModule2.conv26.bias", "EnhanceModule2.conv27.weight", "EnhanceModule2.conv27.bias", "EnhanceModule2.conv28.weight", "EnhanceModule2.conv28.bias", "EnhanceModule2.conv29.weight", "EnhanceModule2.conv29.bias", "EnhanceModule2.Enhance_deconv2.weight", "EnhanceModule2.Enhance_deconv2.bias", "EnhanceModule2.Enhanceout0.weight", "EnhanceModule2.Enhanceout0.bias", "EnhanceModule2.Enhanceout1.weight", "EnhanceModule2.Enhanceout1.bias". 
	Unexpected key(s) in state_dict: "EnhanceModule0.feature_block0.resblock0.model.0.weight", "EnhanceModule0.feature_block0.resblock0.model.0.bias", "EnhanceModule0.feature_block0.resblock0.model.2.weight", "EnhanceModule0.feature_block0.resblock0.model.2.bias", "EnhanceModule0.feature_block0.complex_block.complex_conv0.conv_r.weight", "EnhanceModule0.feature_block0.complex_block.complex_conv0.conv_r.bias", "EnhanceModule0.feature_block0.complex_block.complex_conv0.conv_i.weight", "EnhanceModule0.feature_block0.complex_block.complex_conv0.conv_i.bias", "EnhanceModule0.feature_block0.complex_block.complex_conv1.conv_r.weight", "EnhanceModule0.feature_block0.complex_block.complex_conv1.conv_r.bias", "EnhanceModule0.feature_block0.complex_block.complex_conv1.conv_i.weight", "EnhanceModule0.feature_block0.complex_block.complex_conv1.conv_i.bias", "EnhanceModule0.feature_block0.complex_block.complex_conv2.conv_r.weight", "EnhanceModule0.feature_block0.complex_block.complex_conv2.conv_r.bias", "EnhanceModule0.feature_block0.complex_block.complex_conv2.conv_i.weight", "EnhanceModule0.feature_block0.complex_block.complex_conv2.conv_i.bias", "EnhanceModule0.feature_block0.resblock1.model.0.weight", "EnhanceModule0.feature_block0.resblock1.model.0.bias", "EnhanceModule0.feature_block0.resblock1.model.2.weight", "EnhanceModule0.feature_block0.resblock1.model.2.bias", "EnhanceModule0.down_sampling.weight", "EnhanceModule0.down_sampling.bias", "EnhanceModule0.fft_processing.complex_conv1.conv_r.weight", "EnhanceModule0.fft_processing.complex_conv1.conv_r.bias", "EnhanceModule0.fft_processing.complex_conv1.conv_i.weight", "EnhanceModule0.fft_processing.complex_conv1.conv_i.bias", "EnhanceModule0.fft_processing.complex_block0.complex_conv0.conv_r.weight", "EnhanceModule0.fft_processing.complex_block0.complex_conv0.conv_r.bias", "EnhanceModule0.fft_processing.complex_block0.complex_conv0.conv_i.weight", "EnhanceModule0.fft_processing.complex_block0.complex_conv0.conv_i.bias", "EnhanceModule0.fft_processing.complex_block0.complex_conv1.conv_r.weight", "EnhanceModule0.fft_processing.complex_block0.complex_conv1.conv_r.bias", "EnhanceModule0.fft_processing.complex_block0.complex_conv1.conv_i.weight", "EnhanceModule0.fft_processing.complex_block0.complex_conv1.conv_i.bias", "EnhanceModule0.fft_processing.complex_block0.complex_conv2.conv_r.weight", "EnhanceModule0.fft_processing.complex_block0.complex_conv2.conv_r.bias", "EnhanceModule0.fft_processing.complex_block0.complex_conv2.conv_i.weight", "EnhanceModule0.fft_processing.complex_block0.complex_conv2.conv_i.bias", "EnhanceModule0.fft_processing.complex_block1.complex_conv0.conv_r.weight", "EnhanceModule0.fft_processing.complex_block1.complex_conv0.conv_r.bias", "EnhanceModule0.fft_processing.complex_block1.complex_conv0.conv_i.weight", "EnhanceModule0.fft_processing.complex_block1.complex_conv0.conv_i.bias", "EnhanceModule0.fft_processing.complex_block1.complex_conv1.conv_r.weight", "EnhanceModule0.fft_processing.complex_block1.complex_conv1.conv_r.bias", "EnhanceModule0.fft_processing.complex_block1.complex_conv1.conv_i.weight", "EnhanceModule0.fft_processing.complex_block1.complex_conv1.conv_i.bias", "EnhanceModule0.fft_processing.complex_block1.complex_conv2.conv_r.weight", "EnhanceModule0.fft_processing.complex_block1.complex_conv2.conv_r.bias", "EnhanceModule0.fft_processing.complex_block1.complex_conv2.conv_i.weight", "EnhanceModule0.fft_processing.complex_block1.complex_conv2.conv_i.bias", "EnhanceModule0.fft_processing.complex_conv2.conv_r.weight", "EnhanceModule0.fft_processing.complex_conv2.conv_r.bias", "EnhanceModule0.fft_processing.complex_conv2.conv_i.weight", "EnhanceModule0.fft_processing.complex_conv2.conv_i.bias", "EnhanceModule0.feature_block1.resblock0.model.0.weight", "EnhanceModule0.feature_block1.resblock0.model.0.bias", "EnhanceModule0.feature_block1.resblock0.model.2.weight", "EnhanceModule0.feature_block1.resblock0.model.2.bias", "EnhanceModule0.feature_block1.complex_block.complex_conv0.conv_r.weight", "EnhanceModule0.feature_block1.complex_block.complex_conv0.conv_r.bias", "EnhanceModule0.feature_block1.complex_block.complex_conv0.conv_i.weight", "EnhanceModule0.feature_block1.complex_block.complex_conv0.conv_i.bias", "EnhanceModule0.feature_block1.complex_block.complex_conv1.conv_r.weight", "EnhanceModule0.feature_block1.complex_block.complex_conv1.conv_r.bias", "EnhanceModule0.feature_block1.complex_block.complex_conv1.conv_i.weight", "EnhanceModule0.feature_block1.complex_block.complex_conv1.conv_i.bias", "EnhanceModule0.feature_block1.complex_block.complex_conv2.conv_r.weight", "EnhanceModule0.feature_block1.complex_block.complex_conv2.conv_r.bias", "EnhanceModule0.feature_block1.complex_block.complex_conv2.conv_i.weight", "EnhanceModule0.feature_block1.complex_block.complex_conv2.conv_i.bias", "EnhanceModule0.feature_block1.resblock1.model.0.weight", "EnhanceModule0.feature_block1.resblock1.model.0.bias", "EnhanceModule0.feature_block1.resblock1.model.2.weight", "EnhanceModule0.feature_block1.resblock1.model.2.bias", "EnhanceModule0.channel_up.conv_r.weight", "EnhanceModule0.channel_up.conv_r.bias", "EnhanceModule0.channel_up.conv_i.weight", "EnhanceModule0.channel_up.conv_i.bias", "EnhanceModule1.Enhance_subsampling0.weight", "EnhanceModule1.Enhance_subsampling0.bias", "EnhanceModule1.Enhance_subsampling1.weight", "EnhanceModule1.Enhance_subsampling1.bias", "EnhanceModule1.Enhance_subsampling2.weight", "EnhanceModule1.Enhance_subsampling2.bias", "EnhanceModule1.conv15.weight", "EnhanceModule1.conv15.bias", "EnhanceModule1.down_channel0.weight", "EnhanceModule1.down_channel0.bias", "EnhanceModule1.down_channel1.weight", "EnhanceModule1.down_channel1.bias", "EnhanceModule1.down_channel2.weight", "EnhanceModule1.down_channel2.bias", "EnhanceModule1.Enhanceout2.weight", "EnhanceModule1.Enhanceout2.bias". 
	size mismatch for conv0.weight: copying a param with shape torch.Size([64, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 192, 3, 3]).
	size mismatch for EnhanceModule0.conv0.weight: copying a param with shape torch.Size([64, 4, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 1, 1]).
	size mismatch for EnhanceModule0.conv0.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for EnhanceModule0.conv1.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 128, 3, 3]).
	size mismatch for EnhanceModule0.conv1.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for EnhanceModule0.conv2.weight: copying a param with shape torch.Size([64, 64, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3]).
	size mismatch for EnhanceModule0.conv2.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for EnhanceModule0.conv3.weight: copying a param with shape torch.Size([64, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 256, 3, 3]).
	size mismatch for EnhanceModule0.conv3.bias: copying a param with shape torch.Size([64]) from checkpoint, the shape in current model is torch.Size([128]).
	size mismatch for EnhanceModule1.conv5.weight: copying a param with shape torch.Size([128, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 128, 1, 1]).
	size mismatch for EnhanceModule1.conv10.weight: copying a param with shape torch.Size([128, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 192, 1, 1]).
	size mismatch for EnhanceModule1.Enhanceout1.weight: copying a param with shape torch.Size([64, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 1]).

**Comment by abcdef2000** [comment]
权重文件和代码均有更新，请尝试新上传的内容

**Comment by Zruto** [comment]
> 权重文件和代码均有更新，请尝试新上传的内容

代码已经更新了，遇到了新的问题
input_img_down_fft = torch.fft.rfftn(input_img_down)
AttributeError: 'builtin_function_or_method' object has no attribute 'rfftn'

**Comment by abcdef2000** [comment]
请参见ReadMe更新torch版本

**Comment by Zruto** [comment]
用了预训练的模型测LOL的测试集 的得到的psnr和ssim分别是：18.1321和0.7389

**Comment by abcdef2000** [comment]
我们算的是Grayscale的PSNR和SSIM不是sRGB

**Comment by Zruto** [comment]
那么请问table 2贴的其他论文里的指标也是用Grayscale 测的吗

**Comment by abcdef2000** [comment]
是的，为了公平比较

**Comment by Zruto** [comment]
好的，感谢
