### ISSUE TITLE
[Import error]

### ISSUE THREAD

**Issue by CaptainEven** [abcdef2000/R2RNet#2]
from pytorch_msssim import ssim
ModuleNotFoundError: No module named 'pytorch_msssim'

**Comment by abcdef2000** [comment]
You should install pytorch_msssim package(pip install pytorch_msssim)

**Comment by CaptainEven** [comment]
@abcdef2000 Thank you for your quick reply! The import problem solved, another one:
```
    global_step = int(load_ckpt[:-4])
ValueError: invalid literal for int() with base 10: 'Decom'
```

**Comment by abcdef2000** [comment]
Sorry about that, we update the download links of pre-trained models. The models you download should be renamed to numbers like 1.tar.

**Comment by CaptainEven** [comment]
@abcdef2000 It solved! But out of CUDA memory problem occured when testing the 5th 720p image using a 12G memory GPU(Titan XP)

**Comment by abcdef2000** [comment]
Maybe you should use a smaller image size for testing. The size of our testing image is 600x400 (from LOL dataset).

**Comment by CaptainEven** [comment]
@abcdef2000 Thanks for your advice!
