### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by 1senlin** [abcdef2000/R2RNet#3]
大佬好 想请教下我们的数据集我看被取消了 这个能在分享一下吗

**Comment by abcdef2000** [comment]
震惊，我放的不是永久有效的吗，马上哈

**Comment by 1senlin** [comment]
大佬好 能有谷歌网盘上的吗 百度网盘我们被限制了。。。哭😢

**Comment by abcdef2000** [comment]
我被谷歌限制了，我登不上去我的谷歌账号，我也想放在Google drive上，但是。。。。

**Comment by 1senlin** [comment]
好吧好吧 麻烦大佬分享一下数据集 想尝试一下你们的方法 然后看看在我们的场景有没有效 还希望有机会可以跟你交流哈

**Comment by abcdef2000** [comment]
链接已经更新了，可以下载了

**Comment by 1senlin** [comment]
非常感谢
