### ISSUE TITLE
Can you share pre-trained models with other platform?

### ISSUE THREAD

**Issue by cyan-lee** [abcdef2000/R2RNet#4]
Hi.
I tried downloading your pre-trained models and the link required me to log in into Baidu Network.
Unfortunately Baidu sign-up requires a validation code sent to your phone, which seems to be not available outside China.
Can you share the files with other platforms like google drive, dropbox, or something?

**Comment by abcdef2000** [comment]
Unfortunately, due to some limitations, we were unable to share our pre-training models on google drive. We tried again on dropbox, the link to dropbox: https://www.dropbox.com/s/gj6277rjyv3ermh/ckpts.rar?dl=0. We would appreciate it if you would like to help provide a link to google drive.
