### ISSUE TITLE
Train model

### ISSUE THREAD

**Issue by minhthien2206** [abcdef2000/R2RNet#5]
Hi 
I have already downloaded and trained your code again with only DecomNet from the begining. But without loading the pre-trained weight “10.tar”, the model cannot work and the DecomNet gave the result as below
![eval_Decom_22_2](https://user-images.githubusercontent.com/34763839/134794316-d48b9f4a-9dd9-45bc-ba9a-f7700de9bb2d.jpg)
Can you help me with this problem ?

**Comment by abcdef2000** [comment]
You should use predict.py to get results; this is the visualization result not enhanced or decomposition result.
            ''result_1 = self.output_R_denoise
            result_2 = self.output_I_low
            result_3 = self.output_I_delta
            result_4 = self.output_S''
You can get decomposition results result_1 and result_2 by changing cat_image(cat_image = result_4.numpy()) in model.py, you will get your decompositin results in result folder after running predict.py.
