### ISSUE TITLE
不配对的数据集

### ISSUE THREAD

**Issue by paopao-long** [abcdef2000/R2RNet#6]
作者你好，论文中使用的数据集是一个配对低/正常光照图像数据集。那么不配对的数据集可以使用R2RNet进行图像增强吗?

**Comment by abcdef2000** [comment]
我们的方法是基于监督学习，因此只能采用成对的数据，若您的需求是使用不成对的数据来训练模型，可以参考EnlightenGAN(2021 TIP)和Zero-DCE(2020 CVPR)
