### ISSUE TITLE
[Errno 2] No such file or directory: './model\\vgg16.weight'

### ISSUE THREAD

**Issue by nbbllxx0** [abcdef2000/R2RNet#9]
Thanks for your great work! I would like to compare with your results as one of my baselines, however, the vgg16.weight is missing, could U plz update it? That will be of great help

**Comment by abcdef2000** [comment]
Sure, you can download the pre-trained VGG-16 weight from: https://pan.baidu.com/s/1kf1uLjLaAMbfji0fPZKtEQ (code: wmrr).
